version: '3'
services:
  web:
    build:
        context: .
        dockerfile: ./Dockerfile
    volumes:
      - ./app:/src/app
    ports:
      - "5000:5000"
      - "5678:5678"
    env_file: ./app/.env