version: '3.7'
services:
  web:
    build:
        context: .
        dockerfile: ./Dockerfile
    volumes:
      - ./app:/src/app
    ports:
      - "5000:5000"
      - "5678:5678"
    env_file: ./app/.env
    depends_on:
      - db

  db:
    image: postgres:12.8
    expose:
      - 5432
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=pg_db