### Add user
POST http://0.0.0.0:5000/user_test
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
  "first_name": "httpAPIUser",
  "last_name": "string",
  "email": "httpAPIUser@example.com",
  "phone": "string",
  "password": "string",
  "password_confirmation": "string",
  "is_verified": true,
  "user_role_uuid": "758fb334-fe25-40b6-9ac4-98417522afd7"
}

### Delete user
DELETE http://0.0.0.0:5000/user_test/1446e861-7dbf-432d-80be-12849d4fccd1?force=true
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Get user by uuid
GET http://0.0.0.0:5000/user_test/59e49dd8-efb0-4201-b767-607257fd13de
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Get all users
GET http://0.0.0.0:5000/user_test?limit=10&offset=0
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Count users
GET http://0.0.0.0:5000/user_test/count
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### =====Old Way=====
### Get all users
GET http://0.0.0.0:5000/users/
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Get user by uuid
GET http://0.0.0.0:5000/users/94ca4f7e-e4ae-4921-8758-94e672fe201d
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Count users
GET http://0.0.0.0:5000/users/count
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json
