@file_uuid = 498851e8-c4c1-4aef-832b-cf088bfd2f45

### Get all files size
GET {{baseUrl}}/file_test/used_space
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Get all files
GET {{baseUrl}}/file_test
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Get presigned URL
GET {{baseUrl}}/file_test/{{file_uuid}}/presigned_url
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json

### Delete file
DELETE {{baseUrl}}/file_test/{{file_uuid}}
Accept: application/json
tenant: {{tenant}}
Authorization: Bearer {{token}}
Content-Type: application/json
